name: GitLab

on:
  push:
  pull_request:
  merge_group:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: Taucher2003/GitLab-Pipeline-Action@<version>
        name: Run pipeline
        with:
          GL_SERVER_URL: https://gitlab.com
          GL_PROJECT_ID: '52107720'
          GL_RUNNER_TOKEN: ${{ secrets.GL_RUNNER_TOKEN }}
          GL_API_TOKEN: ${{ secrets.GL_API_TOKEN }}
